# Generated by Django 4.2.6 on 2023-10-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Categoría Nueva', verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='Días especiales', verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='medida',
            name='description',
            field=models.TextField(default='S - 15/25 personas', verbose_name='Descripcion'),
        ),
    ]
