# Generated by Django 4.2.6 on 2023-10-26 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medida', verbose_name='medida'),
        ),
    ]
