# Generated by Django 4.2.6 on 2023-10-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='medida',
            field=models.PositiveSmallIntegerField(choices=[(1, 'S - 15/25 personas'), (2, 'M - 25/35 personas'), (3, 'L - 35/50 personas'), (4, 'XL - 50/100 personas'), (5, 'XXL - 100/300 personas')]),
        ),
    ]
