# Generated by Django 4.2.6 on 2023-10-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_medida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='evento',
            new_name='evento_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='medida',
        ),
        migrations.AddField(
            model_name='product',
            name='medida_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.medida', verbose_name='medida'),
        ),
    ]
