# Generated by Django 4.2.6 on 2023-10-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_categoria_product_categoria_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
    ]
